version: "3.9"

services:
  db:
    image: postgres:16
    container_name: efp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ethio_fuel_pass}
      POSTGRES_USER: ${POSTGRES_USER:-ethio_fuel_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ethio_fuel_password}
    ports:
      - "5432:5432"
    volumes:
      - efp-postgres-data:/var/lib/postgresql/data

volumes:
  efp-postgres-data:
